Repository thrindleProjects/amali-inclusion, pull requests merged in 2023-01, with the labels that each got.

#30 Sub agent
  .vscode/settings.json
  src/components/lib/AirtimeModal/AirtimeModal.tsx
  src/components/lib/CheckEligibility/CheckEligibility.tsx
  src/components/lib/CheckEligibility/index.ts
  src/components/lib/CheckEligibility/types.ts
  src/components/lib/ChoosePaymentPlan/ChoosePaymentPlan.tsx
  src/components/lib/ChoosePaymentPlan/index.ts
  src/components/lib/ChoosePaymentPlan/types.ts
  src/components/lib/ConfirmPaymentPlan/ConfirmPaymentPlan.tsx
  src/components/lib/ConfirmPaymentPlan/index.ts
  src/components/lib/ConfirmPaymentPlan/types.ts
  src/components/lib/ConfirmPaymentPlanModal/ConfirmPaymentPlanModal.tsx
  src/components/lib/ConfirmPaymentPlanModal/index.ts
  src/components/lib/ConfirmPaymentPlanModal/types.ts
  src/components/lib/EligibleLoanToast/EligibleLoanToast.tsx
  src/components/lib/EligibleLoanToast/index.ts
  src/components/lib/EligibleLoanToast/types.ts
  src/components/lib/EnterLoanAmount/EnterLoanAmount.tsx
  src/components/lib/EnterLoanAmount/index.ts
  src/components/lib/EnterLoanAmount/types.ts
  src/components/lib/EnterLoanAmount/validation.ts
  src/components/lib/FloatRequestDone/FloatRequestDone.tsx
  src/components/lib/FloatRequestDone/index.ts
  src/components/lib/FloatRequestDone/types.ts
  src/components/lib/IneligibleLoanToast/IneligibleLoanToast.tsx
  src/components/lib/IneligibleLoanToast/index.ts
  src/components/lib/IneligibleLoanToast/types.ts
  src/components/lib/InternetModal/InternetModal.tsx
  src/components/lib/NavItem/NavItem.tsx
  src/components/lib/PaymentPlansList/PaymentPlansList.tsx
  src/components/lib/PaymentPlansList/index.ts
  src/components/lib/PaymentPlansList/types.ts
  src/components/lib/VerifyFloatOTP/VerifyFloatOTP.tsx
  src/components/lib/VerifyFloatOTP/index.ts
  src/components/lib/VerifyFloatOTP/types.ts
  src/components/lib/VerifyFloatOTP/validation.ts
  src/components/pages-layout/sub-agent/float/request/RequestFloatLayout.tsx
  src/components/pages-layout/sub-agent/float/request/index.ts
  src/components/pages-layout/sub-agent/float/request/types.ts
  src/components/pages-layout/sub-agent/float/request/variants.ts
  src/data/data.ts
  src/layout/AuthLayout/AuthLayout.tsx
  src/pages/sub-agent/float/request/index.tsx
  src/styles/globals.css
  src/types/constants.ts
  src/types/navLinks.ts
Labels: enhancement

#31 Fix flows
  next.config.js
  src/components/lib/NavItem/NavItem.tsx
  src/components/lib/loginForm/LoginForm.tsx
  src/components/pages-layout/sub-agent/float/request/RequestFloatLayout.tsx
  src/pages/admin/all-agent/[id].tsx
  src/pages/admin/all-agent/agent.tsx
  src/pages/admin/create-agent.tsx
  src/pages/admin/dashboard.tsx
  src/pages/admin/kyc-manager/[id].tsx
  src/pages/admin/kyc-manager/index.tsx
  src/pages/admin/master-agents.tsx
  src/pages/admin/settings/general-settings.tsx
  src/pages/admin/settings/payment-settings.tsx
  src/pages/admin/settings/profile-settings.tsx
  src/pages/admin/settings/settings.tsx
  src/pages/admin/settings/users.tsx
  src/pages/agent/bills-payment/airtime/index.tsx
  src/pages/agent/bills-payment/cable/index.tsx
  src/pages/agent/bills-payment/electricity/index.tsx
  src/pages/agent/bills-payment/internet/index.tsx
  src/pages/agent/bnpl.tsx
  src/pages/agent/customers/create/index.tsx
  src/pages/agent/customers/index.tsx
  src/pages/agent/dashboard.tsx
  src/pages/agent/float/request/index.tsx
  src/pages/master-agent/add-sub-agent.tsx
  src/pages/master-agent/dashboard.tsx
  src/pages/master-agent/performance.tsx
  src/pages/master-agent/profile.tsx
  src/pages/master-agent/terminals.tsx
  src/pages/master-agent/transactions.tsx
  src/pages/master-agent/wallet-history.tsx
  src/pages/master-agent/withdrawal.tsx
  src/pages/new-layout.tsx
  src/styles/globals.css
  src/types/constants.ts
  src/types/navLinks.ts
Labels: enhancement

#32 Change layout
  src/components/lib/CheckEligibility/CheckEligibility.tsx
  src/components/lib/NavItem/NavItem.tsx
  src/components/pages-layout/bills-payment/airtime/AirtimeLayout.tsx
  src/components/pages-layout/bills-payment/cable/CableLayout.tsx
  src/components/pages-layout/bills-payment/electricity/ElectricityLayout.tsx
  src/components/pages-layout/bills-payment/internet/InternetLayout.tsx
  src/components/pages-layout/master-agent/pos-manager/PosManager.tsx
  src/components/pages-layout/master-agent/pos-manager/terminal_id/TerminalTransactionsLayout.tsx
  src/components/pages-layout/sub-agent/add-sub-agent/AddSubAgentLayout.tsx
  src/components/pages-layout/sub-agent/customer/CustomerLayout.tsx
  src/components/pages-layout/sub-agent/customer/create/CreateCustomerLayout.tsx
  src/components/pages-layout/sub-agent/dashboard.tsx
  src/components/pages-layout/sub-agent/float/request/RequestFloatLayout.tsx
  src/components/shared/NavBar/NavBar.tsx
  src/components/shared/NavBar/Navbar.props.ts
  src/components/shared/SideNav/SideNav.props.ts
  src/components/shared/SideNav/SideNav.tsx
  src/components/shared/SideNav/mobileNav/MobileSideNav.tsx
  src/layout/AuthLayout/AuthLayout.tsx
  src/layout/AuthenticatedLayout/index.tsx
  src/layout/BodyLayout/BodyLayout.tsx
  src/layout/MainContentLayout/MainContentLayout.tsx
  src/layout/MainContentLayout/index.ts
  src/layout/MainContentLayout/types.ts
  src/pages/_app.tsx
  src/pages/admin/all-agent/[id].tsx
  src/pages/admin/all-agent/agent.tsx
  src/pages/admin/create-agent.tsx
  src/pages/admin/dashboard.tsx
  src/pages/admin/kyc-manager/[id].tsx
  src/pages/admin/kyc-manager/index.tsx
  src/pages/admin/master-agents.tsx
  src/pages/admin/settings/general-settings.tsx
  src/pages/admin/settings/payment-settings.tsx
  src/pages/agent/bnpl.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/master-agent/add-sub-agent.tsx
  src/pages/master-agent/dashboard.tsx
  src/pages/master-agent/performance.tsx
  src/pages/master-agent/profile.tsx
  src/pages/master-agent/terminals.tsx
  src/pages/master-agent/transactions.tsx
  src/pages/master-agent/wallet-history.tsx
  src/pages/master-agent/withdrawal.tsx
  src/pages/new-layout.tsx
  src/pages/register.tsx
  src/pages/sub-agent/bnpl.tsx
  src/styles/globals.css
Labels: enhancement

#33 Fix half glitch
  package.json
  src/styles/globals.css
  yarn.lock
Labels: bug

#38 fixes
  src/components/lib/accountDropdown/AccountDropdown.tsx
  src/components/lib/loginForm/LoginForm.tsx
  src/data/data.ts
  src/pages/index.tsx
  src/types/constants.ts
  src/types/navLinks.ts
Labels: bug, enhancement

#39 add toggle button to loan settings
  src/components/lib/CreateFloatSettingsModal/CreateFloatSettingsModal.tsx
  src/components/lib/CreateFloatSettingsModal/types.ts
  src/components/lib/LoanSettingsCard/LoanSettingsCard.tsx
  src/components/lib/LoanSettingsCard/types.ts
  src/components/pages-layout/admin/float/settings/FloatSettingsLayout.tsx
  src/components/pages-layout/admin/float/settings/types.ts
  src/data/data.ts
Labels: enhancement

#40 Fix UI bugs and add navigation to request loan UI
  .eslintrc.js
  .eslintrc.json
  src/components/lib/AirtimeForm/AirtimeForm.tsx
  src/components/lib/AirtimeModal/AirtimeModal.tsx
  src/components/lib/AmountButton/AmountButton.tsx
  src/components/lib/BundleButton/BundleButton.tsx
  src/components/lib/CableForm/CableForm.tsx
  src/components/lib/CablePlansButton/CablePlansButton.tsx
  src/components/lib/CheckEligibility/CheckEligibility.tsx
  src/components/lib/ChoosePaymentPlan/ChoosePaymentPlan.tsx
  src/components/lib/ConfirmPaymentPlan/ConfirmPaymentPlan.tsx
  src/components/lib/ElectricityForm/ElectricityForm.tsx
  src/components/lib/EnterLoanAmount/EnterLoanAmount.tsx
  src/components/lib/FloatProgress/FloatProgress.tsx
  src/components/lib/FloatProgress/index.ts
  src/components/lib/FloatProgress/styled.ts
  src/components/lib/FloatProgress/types.ts
  src/components/lib/InternetForm/InternetForm.tsx
  src/components/lib/InternetModal/InternetModal.tsx
  src/components/lib/NavItem/NavItem.tsx
  src/components/lib/VerifyFloatOTP/VerifyFloatOTP.tsx
  src/components/pages-layout/sub-agent/float/request/RequestFloatLayout.tsx
  src/components/pages-layout/sub-agent/float/request/styles.module.css
  src/components/shared/NavBar/NavBar.tsx
  src/components/shared/SideNav/SideNav.tsx
  src/hooks/useMediaQuery.ts
  src/pages/_app.tsx
  src/pages/admin/dashboard.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: bug, enhancement
